export const ticketsData = [
  // Persona 1 - Datos ficticios completos
  {
    id: 1,
    ticket: "2025 5533001644",
    nombre: "María Fernanda de la Vega Montemayor",
    tiempo: "Hace 2 minutos",
    estado: "activo",
    color: "#b7e6f7",
    detalle: {
      fechaTicket: "26/06/2024",
      nombreAsistente: "María Fernanda López Rivera",
      nombreEvento: "Ceremonia de Graduación - Generación 2025",
      estadoDelTicket: "Éxitoso",
      movimiento: "Solicitud de boletos adicionales",
      descripcion: "Se solicitaron 3 boletos adicionales para el evento.",
      boletos: {
        anteriores: [
          { codigo: "BC 5004", asiento: "Fila A, Asiento 10" },
          { codigo: "BC 5005", asiento: "Fila A, Asiento 11" },
          { codigo: "BC 5006", asiento: "Fila A, Asiento 12" },
        ],
        adicionales: [
          { codigo: "B11", asiento: "Fila B, Asiento 1" },
          { codigo: "B12", asiento: "Fila B, Asiento 2" },
          { codigo: "B13", asiento: "Fila B, Asiento 3" },
        ],
      },
      cantidadPagada: "$2,000 MXN",
      formaPago: "Tarjeta vinculada - Toku",
      responsableCambio: "Atención vía Vilistison",
      fechaPago: "14 de mayo de 2024",
      lugarPago: "Auditorio Central, Universidad Nacional",
      fechaEvento: "25 de junio de 2025 - 17:00 hrs",
      boletosTotales: 360,
      precioBoleto: "$500 MXN",
      fechaDePagos: "1 de marzo de 2024 a 1 de junio de 2025",
      coordinadorEvento: "Mtro. Rogelio Martin Villalobos",
    },
    cliente: {
      nombre: "María Fernanda de la Vega Montemayor",
      estudios: "Bachillerato",
      institución: "TEC MONTERREY CCM",
      boletos: [
        {
          codigo: "BC 5004",
          asiento: "Fila A, Asiento 10",
          status: true,
          retriciones: [{ item: "Vegano" }, { item: "Alergia a marisco" }],
        },
        {
          codigo: "BC 5005",
          asiento: "Fila A, Asiento 11",
          status: true,
          retriciones: [{ item: "Vegano" }, { item: "Alergia a marisco" }],
        },
        {
          codigo: "BC 5006",
          asiento: "Fila A, Asiento 12",
          status: true,
          retriciones: [{ item: "Vegano" }, { item: "Sin glute" }],
        },
        {
          codigo: "BC 5007",
          asiento: "Fila B, Asiento 1",
          status: true,
          retriciones: [{ item: "Vegano" }, { item: "Alergia a nuez" }],
        },
        {
          codigo: "BC 5008",
          asiento: "Fila B, Asiento 2",
          status: true,
          retriciones: [{ item: "Vegetariano" }, { item: "Vegano" }],
        },
        {
          codigo: "BC 5009",
          asiento: "Fila B, Asiento 3",
          status: false,
          retriciones: [{ item: null }],
        },
        {
          codigo: "BC 5010",
          asiento: "Fila B, Asiento 3",
          status: false,
          retriciones: [{ item: null }],
        },
      ],
      responsable: "Alejandra Rivera",
      catidadPedido: "5",
      contactoErme: {
        telefonoER: "52 222 445 0000",
        tutorER: "Alejandra Rivera",
      },
      contacto: {
        telefono: "+52 222 445 9891",
        tutor: "Juan Alfonso Rivera Guillén",
      },
    },
    ticketHistorial: [
      {
        motivo: "Solicitar boletos",
        fecha: "20 abril 2025",
        estado: "pendiente",
      },
      {
        motivo: "Cancelar boletos",
        fecha: "15 abril 2025",
        estado: "exitoso",
      },
      {
        motivo: "Devolución",
        fecha: "10 abril 2025",
        estado: "proceso",
      },
      {
        motivo: "Solicitud de boletos After",
        fecha: "5 abril 2025",
        estado: "exitoso",
      },
    ],
    historialSecuencial: [
      {
        fecha: "12 abril 2025",
        hora: "7:00 AM",
        evento: "Registro completado",
        detalle:
          "Registro finalizado y validado para la Ceremonia de Graduación.",
        responsable: "Atención de Chat Bot",
      },
      {
        fecha: "17 abril 2025",
        hora: "9:00 AM",
        evento: "Enlace de Pago",
        detalle: "Se envió el enlace de pago del evento a María Fernanda.",
        responsable: "Finanzas / Atención de Chat Bot",
      },
      {
        fecha: "18 abril 2025",
        hora: "2:00 PM",
        evento: "Pago completado",
        detalle: "Se registró el pago exitoso de $2,000 MXN.",
        responsable: "Atención de Chat Bot",
      },
      {
        fecha: "20 abril 2025",
        hora: "4:00 PM",
        evento: "Solicitud de boletos adicionales",
        detalle: "El asistente solicitó 3 boletos adicionales.",
        responsable: "María Fernanda / Atención de Chat Bot",
      },
      {
        fecha: "21 abril 2025",
        hora: "2:00 PM",
        evento: "Cambio de nuevos boletos",
        detalle: "Se actualizaron los boletos en el sistema.",
        responsable: "Atención de Chat Bot",
      },
    ],
    chat: [
      {
        remitente: "Cliente",
        nombre: "María Fernanda",
        texto: "Hola, tengo un problema para obtener mis boletos.",
        hora: "1 mayo 2025, 10:40 AM",
      },
      {
        remitente: "Soporte",
        nombre: "Soporte",
        texto: "Hola, te ayudo enseguida. ¿Podrías darme tu número de ticket?",
        hora: "1 mayo 2025, 10:42 AM",
      },
      {
        remitente: "Cliente",
        nombre: "María Fernanda",
        texto:
          "Sí, es el ticket 2025 5533001644, y solicité 3 boletos adicionales.",
        hora: "1 mayo 2025, 10:43 AM",
      },
      {
        remitente: "Soporte",
        nombre: "Soporte",
        texto:
          "Gracias, los boletos adicionales fueron confirmados. Puedes verificarlos en tu registro.",
        hora: "1 mayo 2025, 10:45 AM",
      },
    ],
    pago: {
      estadoGeneral: "Pago completo",
      formaPago: "Tarjeta de crédito vinculada Toku",
      totalBoletos: 6,
      fechaDePago: "12/09/2025",
      totalPagado: "$4,000 MXN",
      fechaVencimiento: "28/09/2025",

      // Detalle de transacciones
      transacciones: [
        {
          fecha: "25/06/2024",
          monto: "$2,000 MXN",
          método: "Tarjeta débito",
          estado: "Pagado",
        },
        {
          fecha: "25/06/2024",
          monto: "$1,200 MXN",
          método: "Tarjeta crédito",
          estado: "Pagado",
        },
        {
          fecha: "25/06/2024",
          monto: "$800 MXN",
          método: "Tarjeta débito",
          estado: "Proceso",
        },
      ],

      // Información adicional del pago
      adicional: {
        devoluciones: "No registradas",
        opcionesDevolucion: [
          "Aplicar devolución total",
          "Aplicar devolución parcial",
        ],
        progresoPago: "100%",
        últimaActualización: "12/09/2025 18:34 HRS",
        responsableRegistro: "Asesor - Daniela Ruíz",
      },

      // Historial de transacciones complementarias
      detalleExtra: [
        {
          fecha: "10/09/2025",
          detalle: "Pago confirmado por sistema automático.",
        },
        {
          fecha: "12/09/2025",
          detalle: "Validación manual del pago final por asesor Daniela Ruíz.",
        },
        {
          fecha: "13/09/2025",
          detalle: "Se genera comprobante de pago digital.",
        },
        {
          fecha: "14/09/2025",
          detalle:
            "Solicitud de cliente para obtener 3 boletos adicionales (3 nuevos).",
        },
        {
          fecha: "15/09/2025",
          detalle: "Actualización de registro: boletos adicionales aprobados.",
        },
        {
          fecha: "17/09/2025",
          detalle: "Revisión final del estatus: pago completo y cerrado.",
        },
      ],
    },
  },
  {
    id: 2,
    ticket: "2025 5533001111",
    nombre: "Luis Alberto Ramírez",
    tiempo: "Hace 5 minutos",
    estado: "activo",
    color: "#b7e6f7",
    detalle: {
      fechaTicket: "01/07/2024",
      nombreAsistente: "Luis Alberto Ramírez",
      nombreEvento: "Fiesta de Fin de Curso",
      estadoDelTicket: "Exitoso",
      movimiento: "Registro inicial",
      descripcion: "Registro y pago de 2 boletos.",
      boletos: {
        anteriores: [
          { codigo: "BC 6001", asiento: "Fila C, Asiento 5" },
          { codigo: "BC 6002", asiento: "Fila C, Asiento 6" },
        ],
        adicionales: [],
      },
      cantidadPagada: "$1,000 MXN",
      formaPago: "Tarjeta de débito",
      responsableCambio: "Soporte",
      fechaPago: "01/07/2024",
      lugarPago: "Salón Principal",
      fechaEvento: "10/07/2024 - 20:00 hrs",
      boletosTotales: 200,
      precioBoleto: "$500 MXN",
      fechaDePagos: "01/06/2024 a 01/07/2024",
      coordinadorEvento: "Lic. Patricia Gómez",
    },
    cliente: {
      nombre: "Luis Alberto Ramírez",
      estudios: "Secundaria",
      institución: "Colegio México",
      boletos: [
        {
          codigo: "BC 6001",
          asiento: "Fila C, Asiento 5",
          status: true,
          retriciones: [{ item: "Vegetariano" }],
        },
        {
          codigo: "BC 6002",
          asiento: "Fila C, Asiento 6",
          status: true,
          retriciones: [{ item: "Sin gluten" }],
        },
      ],
      responsable: "Patricia Gómez",
      catidadPedido: "2",
      contactoErme: {
        telefonoER: "55 1234 5678",
        tutorER: "Patricia Gómez",
      },
      contacto: {
        telefono: "55 8765 4321",
        tutor: "Roberto Ramírez",
      },
    },
    ticketHistorial: [
      { motivo: "Registro", fecha: "01/07/2024", estado: "exitoso" },
    ],
    historialSecuencial: [
      {
        fecha: "01/07/2024",
        hora: "10:00 AM",
        evento: "Registro completado",
        detalle: "Registro y pago exitoso.",
        responsable: "Soporte",
      },
    ],
    chat: [
      {
        remitente: "Cliente",
        nombre: "Luis Alberto",
        texto: "¿Cuándo es el evento?",
        hora: "01/07/2024, 10:05 AM",
      },
      {
        remitente: "Soporte",
        nombre: "Soporte",
        texto: "El 10 de julio a las 20:00 hrs.",
        hora: "01/07/2024, 10:06 AM",
      },
    ],
    pago: {
      estadoGeneral: "Pago completo",
      formaPago: "Tarjeta de débito",
      totalBoletos: 2,
      fechaDePago: "01/07/2024",
      totalPagado: "$1,000 MXN",
      fechaVencimiento: "10/07/2024",
      transacciones: [
        {
          fecha: "01/07/2024",
          monto: "$1,000 MXN",
          método: "Tarjeta débito",
          estado: "Pagado",
        },
      ],
      adicional: {
        devoluciones: "No registradas",
        opcionesDevolucion: [],
        progresoPago: "100%",
        últimaActualización: "01/07/2024 10:10 HRS",
        responsableRegistro: "Soporte",
      },
      detalleExtra: [{ fecha: "01/07/2024", detalle: "Pago confirmado." }],
    },
  },
  // Persona 2 - Datos ficticios completos
  {
    id: 3,
    ticket: "2025 5533002222",
    nombre: "Andrea Sofía Martínez",
    tiempo: "Hace 10 minutos",
    estado: "urgente",
    color: "#f7b7b7",
    detalle: {
      fechaTicket: "02/07/2024",
      nombreAsistente: "Andrea Sofía Martínez",
      nombreEvento: "Concierto Primavera",
      estadoDelTicket: "Pendiente",
      movimiento: "Solicitud de boletos",
      descripcion: "Solicitó 4 boletos, pago pendiente.",
      boletos: {
        anteriores: [],
        adicionales: [
          { codigo: "BC 7001", asiento: "Fila D, Asiento 1" },
          { codigo: "BC 7002", asiento: "Fila D, Asiento 2" },
          { codigo: "BC 7003", asiento: "Fila D, Asiento 3" },
          { codigo: "BC 7004", asiento: "Fila D, Asiento 4" },
        ],
      },
      cantidadPagada: "$0 MXN",
      formaPago: "Pendiente",
      responsableCambio: "Soporte",
      fechaPago: "",
      lugarPago: "Teatro Municipal",
      fechaEvento: "20/07/2024 - 19:00 hrs",
      boletosTotales: 400,
      precioBoleto: "$350 MXN",
      fechaDePagos: "02/07/2024 a 20/07/2024",
      coordinadorEvento: "Ing. Mario Torres",
    },
    cliente: {
      nombre: "Andrea Sofía Martínez",
      estudios: "Preparatoria",
      institución: "Prepa Nacional",
      boletos: [
        {
          codigo: "BC 7001",
          asiento: "Fila D, Asiento 1",
          status: false,
          retriciones: [{ item: null }],
        },
        {
          codigo: "BC 7002",
          asiento: "Fila D, Asiento 2",
          status: false,
          retriciones: [{ item: null }],
        },
        {
          codigo: "BC 7003",
          asiento: "Fila D, Asiento 3",
          status: false,
          retriciones: [{ item: null }],
        },
        {
          codigo: "BC 7004",
          asiento: "Fila D, Asiento 4",
          status: false,
          retriciones: [{ item: null }],
        },
      ],
      responsable: "Mario Torres",
      catidadPedido: "4",
      contactoErme: {
        telefonoER: "55 2222 3333",
        tutorER: "Mario Torres",
      },
      contacto: {
        telefono: "55 3333 2222",
        tutor: "Sofía Martínez",
      },
    },
    ticketHistorial: [
      {
        motivo: "Solicitud de boletos",
        fecha: "02/07/2024",
        estado: "pendiente",
      },
    ],
    historialSecuencial: [
      {
        fecha: "02/07/2024",
        hora: "11:00 AM",
        evento: "Solicitud registrada",
        detalle: "Solicitud de 4 boletos.",
        responsable: "Soporte",
      },
    ],
    chat: [
      {
        remitente: "Cliente",
        nombre: "Andrea Sofía Martínez",
        texto: "¿Cuándo debo pagar?",
        hora: "02/07/2024, 11:05 AM",
      },
      {
        remitente: "Soporte",
        nombre: "Soporte",
        texto: "Antes del 20 de julio.",
        hora: "02/07/2024, 11:06 AM",
      },
    ],
    pago: {
      estadoGeneral: "Pendiente",
      formaPago: "Pendiente",
      totalBoletos: 4,
      fechaDePago: "",
      totalPagado: "$0 MXN",
      fechaVencimiento: "20/07/2024",
      transacciones: [],
      adicional: {
        devoluciones: "No registradas",
        opcionesDevolucion: [],
        progresoPago: "0%",
        últimaActualización: "02/07/2024 11:10 HRS",
        responsableRegistro: "Soporte",
      },
      detalleExtra: [],
    },
  },
  // Persona 3 - Datos ficticios completos
  {
    id: 4,
    ticket: "2025 5533003333",
    nombre: "Jorge Enrique Salinas",
    tiempo: "Hace 15 minutos",
    estado: "activo",
    color: "#b7e6f7",
    detalle: {
      fechaTicket: "03/07/2024",
      nombreAsistente: "Jorge Enrique Salinas",
      nombreEvento: "Taller de Robótica",
      estadoDelTicket: "Exitoso",
      movimiento: "Pago y registro",
      descripcion: "Pago de 1 boleto para el taller.",
      boletos: {
        anteriores: [],
        adicionales: [{ codigo: "BC 8001", asiento: "Fila E, Asiento 10" }],
      },
      cantidadPagada: "$600 MXN",
      formaPago: "Transferencia",
      responsableCambio: "Soporte",
      fechaPago: "03/07/2024",
      lugarPago: "Laboratorio 2",
      fechaEvento: "15/07/2024 - 09:00 hrs",
      boletosTotales: 50,
      precioBoleto: "$600 MXN",
      fechaDePagos: "03/07/2024 a 15/07/2024",
      coordinadorEvento: "Mtra. Laura Pérez",
    },
    cliente: {
      nombre: "Jorge Enrique Salinas",
      estudios: "Universidad",
      institución: "UNAM",
      boletos: [
        {
          codigo: "BC 8001",
          asiento: "Fila E, Asiento 10",
          status: true,
          retriciones: [{ item: "Sin lactosa" }],
        },
      ],
      responsable: "Laura Pérez",
      catidadPedido: "1",
      contactoErme: {
        telefonoER: "55 4444 5555",
        tutorER: "Laura Pérez",
      },
      contacto: {
        telefono: "55 5555 4444",
        tutor: "Enrique Salinas",
      },
    },
    ticketHistorial: [
      { motivo: "Pago", fecha: "03/07/2024", estado: "exitoso" },
    ],
    historialSecuencial: [
      {
        fecha: "03/07/2024",
        hora: "12:00 PM",
        evento: "Pago registrado",
        detalle: "Pago de $600 MXN.",
        responsable: "Soporte",
      },
    ],
    chat: [
      {
        remitente: "Cliente",
        nombre: "Jorge Enrique",
        texto: "¿Dónde es el taller?",
        hora: "03/07/2024, 12:05 PM",
      },
      {
        remitente: "Soporte",
        nombre: "Soporte",
        texto: "En Laboratorio 2.",
        hora: "03/07/2024, 12:06 PM",
      },
    ],
    pago: {
      estadoGeneral: "Pago completo",
      formaPago: "Transferencia",
      totalBoletos: 1,
      fechaDePago: "03/07/2024",
      totalPagado: "$600 MXN",
      fechaVencimiento: "15/07/2024",
      transacciones: [
        {
          fecha: "03/07/2024",
          monto: "$600 MXN",
          método: "Transferencia",
          estado: "Pagado",
        },
      ],
      adicional: {
        devoluciones: "No registradas",
        opcionesDevolucion: [],
        progresoPago: "100",
        últimaActualización: "03/07/2024 12:10 HRS",
        responsableRegistro: "Soporte",
      },
      detalleExtra: [{ fecha: "03/07/2024", detalle: "Pago confirmado." }],
    },
  },
  // Los demás con estructura pero sin datos
  {
    id: 5,
    ticket: "2025 5533001896",
    nombre: "",
    tiempo: "",
    estado: "",
    color: "",
    detalle: {
      fechaTicket: "",
      nombreAsistente: "",
      nombreEvento: "",
      estadoDelTicket: "",
      movimiento: "",
      descripcion: "",
      boletos: { anteriores: [], adicionales: [] },
      cantidadPagada: "",
      formaPago: "",
      responsableCambio: "",
      fechaPago: "",
      lugarPago: "",
      fechaEvento: "",
      boletosTotales: null,
      precioBoleto: "",
      fechaDePagos: "",
      coordinadorEvento: "",
    },
    cliente: {
      nombre: "",
      estudios: "",
      institución: "",
      boletos: [],
      responsable: "",
      catidadPedido: "",
      contactoErme: { telefonoER: "", tutorER: "" },
      contacto: { telefono: "", tutor: "" },
    },
    ticketHistorial: [],
    historialSecuencial: [],
    chat: [],
    pago: {
      estadoGeneral: "",
      formaPago: "",
      totalBoletos: null,
      fechaDePago: "",
      totalPagado: "",
      fechaVencimiento: "",
      transacciones: [],
      adicional: {
        devoluciones: "",
        opcionesDevolucion: [],
        progresoPago: "",
        últimaActualización: "",
        responsableRegistro: "",
      },
      detalleExtra: [],
    },
  },
  {
    id: 6,
    ticket: "2025 5533000713",
    nombre: "",
    tiempo: "",
    estado: "",
    color: "",
    detalle: {
      fechaTicket: "",
      nombreAsistente: "",
      nombreEvento: "",
      estadoDelTicket: "",
      movimiento: "",
      descripcion: "",
      boletos: { anteriores: [], adicionales: [] },
      cantidadPagada: "",
      formaPago: "",
      responsableCambio: "",
      fechaPago: "",
      lugarPago: "",
      fechaEvento: "",
      boletosTotales: null,
      precioBoleto: "",
      fechaDePagos: "",
      coordinadorEvento: "",
    },
    cliente: {
      nombre: "",
      estudios: "",
      institución: "",
      boletos: [],
      responsable: "",
      catidadPedido: "",
      contactoErme: { telefonoER: "", tutorER: "" },
      contacto: { telefono: "", tutor: "" },
    },
    ticketHistorial: [],
    historialSecuencial: [],
    chat: [],
    pago: {
      estadoGeneral: "",
      formaPago: "",
      totalBoletos: null,
      fechaDePago: "",
      totalPagado: "",
      fechaVencimiento: "",
      transacciones: [],
      adicional: {
        devoluciones: "",
        opcionesDevolucion: [],
        progresoPago: "",
        últimaActualización: "",
        responsableRegistro: "",
      },
      detalleExtra: [],
    },
  },
  {
    id: 7,
    ticket: "2025 5533001645",
    nombre: "",
    tiempo: "",
    estado: "",
    color: "",
    detalle: {
      fechaTicket: "",
      nombreAsistente: "",
      nombreEvento: "",
      estadoDelTicket: "",
      movimiento: "",
      descripcion: "",
      boletos: { anteriores: [], adicionales: [] },
      cantidadPagada: "",
      formaPago: "",
      responsableCambio: "",
      fechaPago: "",
      lugarPago: "",
      fechaEvento: "",
      boletosTotales: null,
      precioBoleto: "",
      fechaDePagos: "",
      coordinadorEvento: "",
    },
    cliente: {
      nombre: "",
      estudios: "",
      institución: "",
      boletos: [],
      responsable: "",
      catidadPedido: "",
      contactoErme: { telefonoER: "", tutorER: "" },
      contacto: { telefono: "", tutor: "" },
    },
    ticketHistorial: [],
    historialSecuencial: [],
    chat: [],
    pago: {
      estadoGeneral: "",
      formaPago: "",
      totalBoletos: null,
      fechaDePago: "",
      totalPagado: "",
      fechaVencimiento: "",
      transacciones: [],
      adicional: {
        devoluciones: "",
        opcionesDevolucion: [],
        progresoPago: "",
        últimaActualización: "",
        responsableRegistro: "",
      },
      detalleExtra: [],
    },
  },
  {
    id: 8,
    ticket: "2025 5533002570",
    nombre: "",
    tiempo: "",
    estado: "",
    color: "",
    detalle: {
      fechaTicket: "",
      nombreAsistente: "",
      nombreEvento: "",
      estadoDelTicket: "",
      movimiento: "",
      descripcion: "",
      boletos: { anteriores: [], adicionales: [] },
      cantidadPagada: "",
      formaPago: "",
      responsableCambio: "",
      fechaPago: "",
      lugarPago: "",
      fechaEvento: "",
      boletosTotales: null,
      precioBoleto: "",
      fechaDePagos: "",
      coordinadorEvento: "",
    },
    cliente: {
      nombre: "",
      estudios: "",
      institución: "",
      boletos: [],
      responsable: "",
      catidadPedido: "",
      contactoErme: { telefonoER: "", tutorER: "" },
      contacto: { telefono: "", tutor: "" },
    },
    ticketHistorial: [],
    historialSecuencial: [],
    chat: [],
    pago: {
      estadoGeneral: "",
      formaPago: "",
      totalBoletos: null,
      fechaDePago: "",
      totalPagado: "",
      fechaVencimiento: "",
      transacciones: [],
      adicional: {
        devoluciones: "",
        opcionesDevolucion: [],
        progresoPago: "",
        últimaActualización: "",
        responsableRegistro: "",
      },
      detalleExtra: [],
    },
  },
  {
    id: 9,
    ticket: "2025 5533009785",
    nombre: "",
    tiempo: "",
    estado: "",
    color: "",
    detalle: {
      fechaTicket: "",
      nombreAsistente: "",
      nombreEvento: "",
      estadoDelTicket: "",
      movimiento: "",
      descripcion: "",
      boletos: { anteriores: [], adicionales: [] },
      cantidadPagada: "",
      formaPago: "",
      responsableCambio: "",
      fechaPago: "",
      lugarPago: "",
      fechaEvento: "",
      boletosTotales: null,
      precioBoleto: "",
      fechaDePagos: "",
      coordinadorEvento: "",
    },
    cliente: {
      nombre: "",
      estudios: "",
      institución: "",
      boletos: [],
      responsable: "",
      catidadPedido: "",
      contactoErme: { telefonoER: "", tutorER: "" },
      contacto: { telefono: "", tutor: "" },
    },
    ticketHistorial: [],
    historialSecuencial: [],
    chat: [],
    pago: {
      estadoGeneral: "",
      formaPago: "",
      totalBoletos: null,
      fechaDePago: "",
      totalPagado: "",
      fechaVencimiento: "",
      transacciones: [],
      adicional: {
        devoluciones: "",
        opcionesDevolucion: [],
        progresoPago: "",
        últimaActualización: "",
        responsableRegistro: "",
      },
      detalleExtra: [],
    },
  },
  // Puedes agregar más objetos vacíos si necesitas más personas
];
